#!/usr/bin/env python3
from math import isqrt

def solve():
    limit = 1_000_000_000
    total = 0
    # Almost equilateral triangles with sides (a, a, a±1)
    # Area = (a±1)/4 * sqrt(4a^2 - (a±1)^2) using Heron's formula
    # For integer area, sqrt(4a^2 - (a±1)^2) must be integer
    # For (a,a,a+1): need 4a^2 - (a+1)^2 = 3a^2 - 2a - 1 to be a perfect square
    # For (a,a,a-1): need 4a^2 - (a-1)^2 = 3a^2 + 2a - 1 to be a perfect square

    # Use Pell equation approach
    # For (a,a,a+1): 3a^2 - 2a - 1 = y^2 => 3(a-1/3)^2 - 4/3 = y^2
    # This is a Pell-type equation. The solutions are generated by recurrence.
    
    # Known recurrence for (a,a,a+1):
    a1, a2 = 1, 5  # a=5 gives sides (5,5,6) with area 12
    while 3 * a2 + 1 <= limit:
        # Perimeter = 3a + 1, check if valid
        if a2 > 1:
            total += 3 * a2 + 1
        a1, a2 = a2, 4 * a2 - a1 + 2
    
    # For (a,a,a-1):
    a1, a2 = 1, 17  # a=17 gives sides (17,17,16)
    while 3 * a2 - 1 <= limit:
        if a2 > 1:
            total += 3 * a2 - 1
        a1, a2 = a2, 4 * a2 - a1 - 2

    return total

if __name__ == "__main__":
    print(solve())
