#!/usr/bin/env python3

def solve():
    target = 15
    # u^2 - 5v^2 = -4
    # Fundamental solutions: (1,1), (4,2), (11,5), (29,13), ...
    # Generate all from fundamental unit (9,4)
    
    # Start with fundamental solutions
    seeds = [(1, 1), (4, 2), (11, 5)]
    # Also need negative u to generate more? No, we just need positive solutions.
    # Actually the full set of fundamental solutions modulo the unit group
    # includes (1,1), (4,2), (11,5) and also (29,13), (76,34), (199,89)...
    # But some of these are generated by multiplying fundamental ones by (9+4√5)
    
    nuggets = []
    
    for u0, v0 in [(1,1), (4,2), (11,5)]:
        u, v = u0, v0
        while True:
            if u > 0:
                n = (u - 1) // 5
                if n > 0 and (u - 1) % 5 == 0:
                    nuggets.append(n)
            # Multiply by (9+4√5)
            u_new = 9 * u + 20 * v
            v_new = 4 * u + 9 * v
            u, v = u_new, v_new
            if u > 10 ** 30:  # enough
                break
    
    nuggets = sorted(set(nuggets))
    return nuggets[target - 1]  # 15th

if __name__ == "__main__":
    print(solve())
