#!/usr/bin/env python3
from math import exp, isqrt, log
import sys

FACTORS = 1_000_000
RANK = 1_000_000
MOD = 123_454_321

# The millionth ratio is below exp(11.4).  This leaves more than enough
# headroom, while keeping the generated prefix close to one million entries.
LOG_LIMIT = 11.4
EPS = 1e-12


def primes_upto(limit):
    sieve = bytearray(b"\x01") * (limit + 1)
    sieve[:2] = b"\x00\x00"
    for p in range(2, isqrt(limit) + 1):
        if sieve[p]:
            start = p * p
            sieve[start : limit + 1 : p] = b"\x00" * ((limit - start) // p + 1)
    return [n for n in range(limit + 1) if sieve[n]]


def solve():
    # Divide every candidate by 2^FACTORS.  Replacing one of the base twos by
    # an odd prime p costs p/2; adding one extra prime factor 2 costs 2.
    # Thus the early candidates are the sorted products generated by
    # 3/2, 2, 5/2, 7/2, ...
    prime_limit = int(2 * exp(LOG_LIMIT)) + 10
    generators = [(log(2), 1, 1)]
    generators.extend(
        (log(p / 2), p, -1)
        for p in primes_upto(prime_limit)
        if p > 2 and log(p / 2) <= LOG_LIMIT + EPS
    )
    generators.sort()

    sys.setrecursionlimit(1_000_000)
    ratios = []

    def enumerate_ratios(pos, remaining, odd_part, two_power):
        if pos == len(generators) or generators[pos][0] > remaining + EPS:
            ratios.append((odd_part, two_power))
            return

        step_log, odd_multiplier, two_delta = generators[pos]
        enumerate_ratios(pos + 1, remaining, odd_part, two_power)

        next_remaining = remaining - step_log
        next_odd = odd_part * odd_multiplier
        next_two_power = two_power + two_delta
        while next_remaining >= -EPS:
            enumerate_ratios(pos + 1, next_remaining, next_odd, next_two_power)
            next_remaining -= step_log
            next_odd *= odd_multiplier
            next_two_power += two_delta

    enumerate_ratios(0, LOG_LIMIT, 1, 0)
    if len(ratios) < RANK:
        raise RuntimeError("log limit did not cover enough candidates")

    min_two_power = min(two_power for _, two_power in ratios)
    ratios.sort(key=lambda item: item[0] << (item[1] - min_two_power))

    odd_part, two_power = ratios[RANK - 1]
    return odd_part * pow(2, FACTORS + two_power, MOD) % MOD


if __name__ == "__main__":
    print(solve())
