// Project Euler 840: G is generated by prod_m (1-D(m)x^m)^-1.
// The logarithmic derivative gives
//   n G[n] = sum_{j=1}^n c[j] G[n-j],
//   c[j] = sum_{d|j} d D(d)^(j/d).
// Solve the recurrence by CDQ divide-and-conquer convolution.
#include <algorithm>
#include <cstdlib>
#include <cstdint>
#include <cstdio>
#include <iostream>
#include <vector>

using namespace std;

static const int TARGET = 999676999;

static int64_t mod_pow(int64_t a, int64_t e, int mod) {
    int64_t r = 1;
    a %= mod;
    while (e) {
        if (e & 1) r = r * a % mod;
        a = a * a % mod;
        e >>= 1;
    }
    return r;
}

static int64_t egcd(int64_t a, int64_t b, int64_t& x, int64_t& y) {
    if (!b) {
        x = 1;
        y = 0;
        return a;
    }
    int64_t x1, y1;
    int64_t g = egcd(b, a % b, x1, y1);
    x = y1;
    y = x1 - (a / b) * y1;
    return g;
}

static int inv_mod_target(int a) {
    int64_t x, y;
    int64_t g = egcd(a, TARGET, x, y);
    if (g != 1) {
        fprintf(stderr, "non-invertible denominator %d\n", a);
        exit(1);
    }
    x %= TARGET;
    if (x < 0) x += TARGET;
    return (int)x;
}

template <int MOD, int ROOT>
static void ntt(vector<int>& a, bool invert) {
    int n = (int)a.size();
    for (int i = 1, j = 0; i < n; ++i) {
        int bit = n >> 1;
        for (; j & bit; bit >>= 1) j ^= bit;
        j ^= bit;
        if (i < j) swap(a[i], a[j]);
    }
    for (int len = 2; len <= n; len <<= 1) {
        int wlen = (int)mod_pow(ROOT, (MOD - 1) / len, MOD);
        if (invert) wlen = (int)mod_pow(wlen, MOD - 2, MOD);
        for (int i = 0; i < n; i += len) {
            int64_t w = 1;
            for (int j = 0; j < len / 2; ++j) {
                int u = a[i + j];
                int v = (int)(w * a[i + j + len / 2] % MOD);
                int x = u + v;
                if (x >= MOD) x -= MOD;
                int y = u - v;
                if (y < 0) y += MOD;
                a[i + j] = x;
                a[i + j + len / 2] = y;
                w = w * wlen % MOD;
            }
        }
    }
    if (invert) {
        int inv_n = (int)mod_pow(n, MOD - 2, MOD);
        for (int& x : a) x = (int)((int64_t)x * inv_n % MOD);
    }
}

template <int MOD, int ROOT>
static vector<int> convolution_prime(const vector<int>& a, const vector<int>& b) {
    int need = (int)a.size() + (int)b.size() - 1;
    int n = 1;
    while (n < need) n <<= 1;
    vector<int> fa(n), fb(n);
    for (size_t i = 0; i < a.size(); ++i) fa[i] = a[i] % MOD;
    for (size_t i = 0; i < b.size(); ++i) fb[i] = b[i] % MOD;
    ntt<MOD, ROOT>(fa, false);
    ntt<MOD, ROOT>(fb, false);
    for (int i = 0; i < n; ++i) fa[i] = (int)((int64_t)fa[i] * fb[i] % MOD);
    ntt<MOD, ROOT>(fa, true);
    fa.resize(need);
    return fa;
}

static vector<int> convolution_target(const vector<int>& a, const vector<int>& b) {
    if (a.empty() || b.empty()) return {};
    if ((uint64_t)a.size() * b.size() <= 40000) {
        vector<int> out(a.size() + b.size() - 1);
        for (size_t i = 0; i < a.size(); ++i) {
            if (!a[i]) continue;
            for (size_t j = 0; j < b.size(); ++j) {
                out[i + j] = (out[i + j] + (int64_t)a[i] * b[j]) % TARGET;
            }
        }
        return out;
    }

    static const int P1 = 998244353, R1 = 3;
    static const int P2 = 1004535809, R2 = 3;
    static const int P3 = 469762049, R3 = 3;
    vector<int> r1 = convolution_prime<P1, R1>(a, b);
    vector<int> r2 = convolution_prime<P2, R2>(a, b);
    vector<int> r3 = convolution_prime<P3, R3>(a, b);

    int64_t inv_p1_p2 = mod_pow(P1, P2 - 2, P2);
    int64_t p1p2_mod_p3 = (int64_t)(P1 % P3) * (P2 % P3) % P3;
    int64_t inv_p1p2_p3 = mod_pow(p1p2_mod_p3, P3 - 2, P3);
    int64_t p1_mod_target = P1 % TARGET;
    int64_t p1p2_mod_target = (int64_t)(P1 % TARGET) * (P2 % TARGET) % TARGET;

    vector<int> out(r1.size());
    for (size_t i = 0; i < out.size(); ++i) {
        int64_t t1 = (r2[i] - r1[i]) % P2;
        if (t1 < 0) t1 += P2;
        t1 = t1 * inv_p1_p2 % P2;

        int64_t x12_mod_p3 = (r1[i] + (int64_t)(P1 % P3) * (t1 % P3)) % P3;
        int64_t t2 = (r3[i] - x12_mod_p3) % P3;
        if (t2 < 0) t2 += P3;
        t2 = t2 * inv_p1p2_p3 % P3;

        out[i] = (int)((r1[i] % TARGET +
                        (__int128)p1_mod_target * t1 % TARGET +
                        (__int128)p1p2_mod_target * t2 % TARGET) %
                       TARGET);
    }
    return out;
}

static vector<int> coeffs;
static vector<int> g_values;
static vector<int> invs;

static void cdq(int l, int r) {
    if (l == r) {
        if (l > 0) g_values[l] = (int)((int64_t)g_values[l] * invs[l] % TARGET);
        return;
    }
    int mid = (l + r) / 2;
    cdq(l, mid);

    vector<int> a(g_values.begin() + l, g_values.begin() + mid + 1);
    vector<int> b(coeffs.begin() + 1, coeffs.begin() + (r - l + 1));
    vector<int> conv = convolution_target(a, b);
    for (int n = mid + 1; n <= r; ++n) {
        int idx = n - l - 1;
        if (idx >= 0 && idx < (int)conv.size()) {
            g_values[n] += conv[idx];
            if (g_values[n] >= TARGET) g_values[n] -= TARGET;
        }
    }
    cdq(mid + 1, r);
}

static vector<int> arithmetic_derivative_values(int n) {
    vector<int> spf(n + 1);
    for (int i = 0; i <= n; ++i) spf[i] = i;
    for (int i = 2; (int64_t)i * i <= n; ++i) {
        if (spf[i] != i) continue;
        for (int64_t j = (int64_t)i * i; j <= n; j += i)
            if (spf[(int)j] == j) spf[(int)j] = i;
    }

    vector<int> d(n + 1);
    d[1] = 1;
    for (int x = 2; x <= n; ++x) {
        int t = x;
        int64_t value = 0;
        while (t > 1) {
            int p = spf[t];
            while (t % p == 0) {
                t /= p;
                value += x / p;
            }
        }
        d[x] = (int)(value % TARGET);
    }
    return d;
}

static int solve_limit(int n) {
    vector<int> d = arithmetic_derivative_values(n);
    coeffs.assign(n + 1, 0);
    for (int part = 1; part <= n; ++part) {
        int64_t power = 1;
        int w = d[part];
        for (int j = part; j <= n; j += part) {
            power = power * w % TARGET;
            coeffs[j] = (coeffs[j] + (int64_t)part * power) % TARGET;
        }
    }

    invs.assign(n + 1, 0);
    for (int i = 1; i <= n; ++i) invs[i] = inv_mod_target(i);
    g_values.assign(n + 1, 0);
    g_values[0] = 1;
    cdq(0, n);

    int total = 0;
    for (int i = 1; i <= n; ++i) {
        total += g_values[i];
        if (total >= TARGET) total -= TARGET;
    }
    return total;
}

int main() {
    if (g_values.size()) return 1;
    int sample = solve_limit(10);
    if (g_values[10] != 164 || sample != 396) {
        fprintf(stderr, "self-test failed: G10=%d S10=%d\n", g_values[10], sample);
        return 1;
    }
    printf("%d\n", solve_limit(50000));
    return 0;
}
